### ISSUE TITLE
Jar files are not available  

### ISSUE THREAD

**Issue by Bujjigit** [zowe/rest-api-jzos-sample#2]
Hi ,

I have tried to add the jzos sample to Zowe ,but when I tried to do maven build on eclipse I am facing an error with ibmjzos.jar and I didn't find the utilities.jar.Can you please help me to resolve the errors.

Thanks,
Bujji

**Comment by stevenhorsman** [comment]
I think we are addressing this in 1.0, by updating/removing the sample
